// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PointFlow.Model;

#nullable disable

namespace PointFlow.Model.Migrations
{
    [DbContext(typeof(PointFlowDbContext))]
    partial class PointFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PointFlow.Model.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentBalance")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalPointsEarned")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentBalance = 150,
                            Email = "ana@example.com",
                            TotalPointsEarned = 320,
                            Username = "ana_k"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentBalance = 80,
                            Email = "marko@example.com",
                            TotalPointsEarned = 200,
                            Username = "marko_p"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentBalance = 260,
                            Email = "petra@example.com",
                            TotalPointsEarned = 510,
                            Username = "petra_v"
                        });
                });

            modelBuilder.Entity("PointFlow.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tasks related to acquiring new knowledge",
                            Name = "Learning"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tasks related to physical health and exercise",
                            Name = "Fitness"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Professional and career-related tasks",
                            Name = "Work"
                        });
                });

            modelBuilder.Entity("PointFlow.Model.PointTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("PointsReward")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Go through chapters 1-5 of the C# guide",
                            IsCompleted = true,
                            PointsReward = 50,
                            Priority = 2,
                            Title = "Study C# fundamentals"
                        },
                        new
                        {
                            Id = 2,
                            AppUserId = 1,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Morning run in the park",
                            IsCompleted = true,
                            PointsReward = 30,
                            Priority = 1,
                            Title = "Run 5km"
                        },
                        new
                        {
                            Id = 3,
                            AppUserId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "At least 30 pages per session",
                            IsCompleted = false,
                            PointsReward = 40,
                            Priority = 0,
                            Title = "Read Clean Code book"
                        },
                        new
                        {
                            Id = 4,
                            AppUserId = 2,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Compile Q1 data and write summary",
                            IsCompleted = false,
                            PointsReward = 60,
                            Priority = 2,
                            Title = "Finish quarterly report"
                        },
                        new
                        {
                            Id = 5,
                            AppUserId = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Upper body workout",
                            IsCompleted = true,
                            PointsReward = 25,
                            Priority = 1,
                            Title = "Gym session"
                        },
                        new
                        {
                            Id = 6,
                            AppUserId = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Deep dive into object-oriented design principles",
                            IsCompleted = true,
                            PointsReward = 70,
                            Priority = 2,
                            Title = "Study SOLID principles"
                        });
                });

            modelBuilder.Entity("PointFlow.Model.PomodoroSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsQuizPassed")
                        .HasColumnType("bit");

                    b.Property<string>("LearnedNotes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PointTaskId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PointTaskId");

                    b.ToTable("PomodoroSessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationMinutes = 25,
                            EndTime = new DateTime(2026, 3, 1, 9, 25, 0, 0, DateTimeKind.Unspecified),
                            IsQuizPassed = true,
                            LearnedNotes = "Covered C# type system: value types vs reference types, boxing/unboxing.",
                            PointTaskId = 1,
                            StartTime = new DateTime(2026, 3, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DurationMinutes = 25,
                            EndTime = new DateTime(2026, 3, 15, 10, 25, 0, 0, DateTimeKind.Unspecified),
                            IsQuizPassed = true,
                            LearnedNotes = "Studied SOLID principles with examples in C#.",
                            PointTaskId = 6,
                            StartTime = new DateTime(2026, 3, 15, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PointFlow.Model.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExpectedAnswer")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PomodoroSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserAnswer")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("PomodoroSessionId");

                    b.ToTable("Quizzes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpectedAnswer = "A class is a reference type allocated on the heap; a struct is a value type allocated on the stack.",
                            PomodoroSessionId = 1,
                            Question = "What is the difference between a class and a struct in C#?",
                            UserAnswer = "Classes are reference types, structs are value types stored on the stack."
                        },
                        new
                        {
                            Id = 2,
                            ExpectedAnswer = "Single responsibility, Open/closed, Liskov substitution, Interface segregation, Dependency inversion.",
                            PomodoroSessionId = 2,
                            Question = "What does SOLID stand for?",
                            UserAnswer = "Single responsibility, Open/closed, Liskov substitution, Interface segregation, Dependency inversion."
                        });
                });

            modelBuilder.Entity("PointFlow.Model.Reward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PointsCost")
                        .HasColumnType("int");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Rewards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = 1,
                            Description = "1 hour of guilt-free Netflix",
                            IsLocked = false,
                            Name = "Netflix evening",
                            PointsCost = 50,
                            UnlockedAt = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AppUserId = 1,
                            Description = "Treat yourself to a new technical book",
                            IsLocked = true,
                            Name = "Buy a new book",
                            PointsCost = 120,
                            UnlockedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AppUserId = 2,
                            Description = "2 hours of gaming without guilt",
                            IsLocked = false,
                            Name = "Gaming session",
                            PointsCost = 60,
                            UnlockedAt = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AppUserId = 2,
                            Description = "Short trip to the mountains",
                            IsLocked = true,
                            Name = "Weekend trip",
                            PointsCost = 300,
                            UnlockedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            AppUserId = 3,
                            Description = "Full relaxation day at the spa",
                            IsLocked = false,
                            Name = "Spa day",
                            PointsCost = 200,
                            UnlockedAt = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            AppUserId = 3,
                            Description = "Enroll in an advanced .NET course",
                            IsLocked = false,
                            Name = "Online course",
                            PointsCost = 150,
                            UnlockedAt = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PointFlow.Model.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Study"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Work"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Health"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Personal"
                        });
                });

            modelBuilder.Entity("PointTaskTags", b =>
                {
                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.Property<int>("TasksId")
                        .HasColumnType("int");

                    b.HasKey("TagsId", "TasksId");

                    b.HasIndex("TasksId");

                    b.ToTable("PointTaskTags");

                    b.HasData(
                        new
                        {
                            TagsId = 1,
                            TasksId = 1
                        },
                        new
                        {
                            TagsId = 3,
                            TasksId = 2
                        },
                        new
                        {
                            TagsId = 1,
                            TasksId = 3
                        },
                        new
                        {
                            TagsId = 4,
                            TasksId = 3
                        },
                        new
                        {
                            TagsId = 2,
                            TasksId = 4
                        },
                        new
                        {
                            TagsId = 3,
                            TasksId = 5
                        },
                        new
                        {
                            TagsId = 1,
                            TasksId = 6
                        },
                        new
                        {
                            TagsId = 2,
                            TasksId = 6
                        });
                });

            modelBuilder.Entity("PointFlow.Model.PointTask", b =>
                {
                    b.HasOne("PointFlow.Model.AppUser", "AppUser")
                        .WithMany("Tasks")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PointFlow.Model.Category", "Category")
                        .WithMany("Tasks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PointFlow.Model.PomodoroSession", b =>
                {
                    b.HasOne("PointFlow.Model.PointTask", "PointTask")
                        .WithMany("PomodoroSessions")
                        .HasForeignKey("PointTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PointTask");
                });

            modelBuilder.Entity("PointFlow.Model.Quiz", b =>
                {
                    b.HasOne("PointFlow.Model.PomodoroSession", "PomodoroSession")
                        .WithMany("Quizzes")
                        .HasForeignKey("PomodoroSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PomodoroSession");
                });

            modelBuilder.Entity("PointFlow.Model.Reward", b =>
                {
                    b.HasOne("PointFlow.Model.AppUser", "AppUser")
                        .WithMany("Rewards")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("PointTaskTags", b =>
                {
                    b.HasOne("PointFlow.Model.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PointFlow.Model.PointTask", null)
                        .WithMany()
                        .HasForeignKey("TasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PointFlow.Model.AppUser", b =>
                {
                    b.Navigation("Rewards");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("PointFlow.Model.Category", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("PointFlow.Model.PointTask", b =>
                {
                    b.Navigation("PomodoroSessions");
                });

            modelBuilder.Entity("PointFlow.Model.PomodoroSession", b =>
                {
                    b.Navigation("Quizzes");
                });
#pragma warning restore 612, 618
        }
    }
}
